-- 1월의 카테고리별 도서 판매량 합산
SELECT 
    CATEGORY, 
    SUM(SALES) AS TOTAL_SALES
FROM 
    BOOK B JOIN BOOK_SALES S 
    USING(BOOK_ID)
WHERE 
    TO_CHAR(SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01-%'
GROUP BY 
    CATEGORY
ORDER BY 
    CATEGORY ASC;